// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FollowTheLinksOfAnUnauthorizedPersonTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void followTheLinksOfAnUnauthorizedPerson() {
        driver.get("https://dfiles.eu/");
        driver.manage().window().setSize(new Dimension(960, 1053));
        driver.findElement(By.xpath("//div[@id=\'member_menu\']/div/div")).click();
        driver.findElement(By.xpath("//a[contains(text(),\'FTP загрузка\')]")).click();
        assertThat(driver.findElement(By.xpath("//form[@id=\'login_frm\']/table/tbody/tr[4]/th")).getText(), is("Логин:"));
        driver.findElement(By.xpath("//a[@id=\'logo\']")).click();
        driver.findElement(By.xpath("//a[contains(text(),\'Удаленная загрузка\')]")).click();
        assertThat(driver.findElement(By.xpath("//form[@id=\'login_frm\']/table/tbody/tr[4]/th")).getText(), is("Логин:"));
        driver.findElement(By.xpath("//a[@id=\'logo\']")).click();
        driver.findElement(By.xpath("//div[@id=\'member_menu\']/div/div/a[4]")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'main\']/div[4]/div[2]/div/p"));
            assert(elements.size() > 0);
        }
    }
}