// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FooterInfoPageTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void footerInfoPage() {
        driver.get("https://dfiles.eu/");
        driver.manage().window().setSize(new Dimension(960, 1053));
        driver.findElement(By.xpath("//a[contains(text(),\'Новости\')]")).click();
        assertThat(driver.findElement(By.xpath("//a[contains(text(),\'Новости\')]")).getText(), is("Новости"));
        driver.findElement(By.xpath("//a[contains(text(),\'Программа лояльности\')]")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'main\']/div[4]/div[2]/div/div/h1/strong"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.xpath("//a[contains(text(),\'DepositTools\')]")).click();
        driver.findElement(By.xpath("//a[contains(text(),\'FAQ\')]")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//a[contains(text(),\'FAQ\')]"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.xpath("(//a[contains(text(),\'О DepositFiles\')])[2]")).click();
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'О DepositFiles\')]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'О DepositFiles\')]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'О DepositFiles\')]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.xpath("//div[@id=\'main\']")).click();
        assertThat(driver.findElement(By.xpath("//a[contains(text(),\'О DepositFiles\')]")).getText(), is("О DepositFiles"));
        driver.findElement(By.xpath("//a[contains(text(),\'Пользовательское соглашение\')]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[4]/div/div/ins")).getText(), is("Пользовательское соглашение"));
        driver.findElement(By.xpath("(//a[contains(text(),\'Политика конфиденциальности\')])[2]")).click();
        driver.findElement(By.xpath("//div[@id=\'main\']/div[4]/div/div/ins")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[4]/div/div/ins")).getText(), is("Политика конфиденциальности"));
    }
}