// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class GroupFileTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        String driverType = System.getenv("DRIVER");
        if(driverType.equals("CHROME")) {
            driver = new ChromeDriver();
        }else if(driverType.equals("FIREFOX")){
            driver = new FirefoxDriver();
        }
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");
        System.setProperty("webdriver.gecko.driver", "/usr/bin/geckodriver");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void groupFile() {
        driver.get("https://dfiles.eu/");
        vars.put("window_handle", driver.getWindowHandle());
        driver.manage().window().setSize(new Dimension(1920, 1053));
        driver.findElement(By.xpath("//div[@id=\'main\']/div/div/a/strong")).click();
        driver.findElement(By.xpath("//input[@name=\'login\']")).click();
        driver.findElement(By.xpath("//input[@name=\'login\']")).sendKeys("gardemarrina");
        driver.findElement(By.xpath("//form[@id=\'login_frm\']/table/tbody/tr[2]/td")).click();
        driver.findElement(By.xpath("//form[@id=\'login_frm\']/table/tbody/tr[3]/td")).click();
        driver.findElement(By.xpath("//form[@id=\'login_frm\']/table/tbody/tr[5]/td")).click();
        driver.findElement(By.xpath("//input[@name=\'password\']")).click();
        driver.findElement(By.xpath("//input[@name=\'password\']")).sendKeys("123456");
        driver.findElement(By.xpath("//form[@id=\'login_frm\']/table/tbody/tr[7]/td")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@id=\'login_btn\']")));
        }
        driver.findElement(By.xpath("//input[@id=\'login_btn\']")).click();
        driver.switchTo().window(vars.get("window_handle").toString());
        {
            WebDriverWait wait = new WebDriverWait(driver, 300);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[contains(@href, \'/gold/files_list.php\')]")));
        }
        driver.findElement(By.xpath("//a[contains(@href, \'/gold/files_list.php\')]")).click();
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'Несортированные\')]"));
            JavascriptExecutor jse = (JavascriptExecutor) driver;
            jse.executeScript("arguments[0].click()", element);
        }
        driver.findElement(By.xpath("//input[@name=\'ids[]\']")).click();
        driver.findElement(By.xpath("(//input[@name=\'ids[]\'])[2]")).click();
        driver.findElement(By.xpath("//div[@id=\'df_share\']/div[2]/div/a[6]/span")).click();
        {
            WebElement element = driver.findElement(By.xpath("//div[@id=\'df_share\']/div[2]/div/a[6]/span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.xpath("(//input[@type=\'text\'])[9]")).click();
        driver.findElement(By.xpath("(//input[@type=\'text\'])[9]")).sendKeys("groupfiles");
        driver.findElement(By.xpath("//div[@id=\'depositbox\']/div/div[2]/div/div")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[contains(@class, \'folder\') and text()=\'groupfiles \']")));
        }
        driver.findElement(By.xpath("//a[contains(@class, \'folder\') and text()=\'groupfiles \']")).click();
                {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("(//input[@name=\'ids[]\'])[2]")));
        }
        driver.findElement(By.xpath("(//input[@name=\'ids[]\'])[2]")).click();
        driver.findElement(By.xpath("//input[@name=\'ids[]\']")).click();
        driver.findElement(By.xpath("//div[@id=\'df_share\']/div[2]/div/a[5]/span")).click();
        driver.findElement(By.xpath("(//a[contains(text(),\'Несортированные\')])[4]")).click();
        driver.findElement(By.xpath("(//input[@name=\'move\'])[2]")).click();
        driver.findElement(By.xpath("//a[contains(@class, \'folder\') and text()=\'groupfiles \']")).click();
        driver.findElement(By.xpath("//div[@id=\'df_share\']/div/div/a[3]/span")).click();
        driver.findElement(By.xpath("(//input[@type=\'text\'])[9]")).click();
        driver.findElement(By.xpath("(//input[@type=\'text\'])[9]")).sendKeys("trash");
        driver.findElement(By.xpath("//div[@id=\'depositbox\']/div/div[2]/div/div")).click();
        driver.findElement(By.xpath("//div[@id=\'main\']/div/div[2]/a[2]/strong")).click();
        driver.findElement(By.xpath("//a[contains(text(),\'Выход\')]")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'main\']/div/div/a/strong")));
        }
        driver.close();
    }
}