// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.anyOf;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RegistrationViaSocialNetvorksTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        String driverType = System.getenv("DRIVER");
        if(driverType.equals("CHROME")) {
            driver = new ChromeDriver();
        }else if(driverType.equals("FIREFOX")){
            driver = new FirefoxDriver();
        }
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");
        System.setProperty("webdriver.gecko.driver", "/usr/bin/geckodriver");
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void registrationViaSocialNetvorks() {
        driver.get("https://dfiles.eu/");
        driver.manage().window().setSize(new Dimension(960, 1053));
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(@class, \'flag_ru\')]"));
            JavascriptExecutor jse = (JavascriptExecutor)driver;
            jse.executeScript("arguments[0].scrollIntoView()", element);
        }
        driver.findElement(By.xpath("//a[contains(@class, \'flag_ru\')]")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[contains(@class, \'active\') and contains(@class, \'flag_ru\')]")));
        }
        driver.findElement(By.xpath("//a[contains(text(),\'Зарегистрируйтесь сейчас!\')]")).click();
        driver.findElement(By.xpath("//input[@id=\'i_undertake_conditions\']")).click();
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector("#signup_frm #facebook")).click();
        vars.put("win2634", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win2634").toString());
        assertThat(driver.findElement(By.xpath("//div[@id=\'header_block\']/span/div")).getText(), anyOf(is("Вход на Facebook"), is("Log in to Facebook")) );
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        driver.findElement(By.cssSelector("#signup_frm .oauth_login")).click();
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector("#signup_frm #twitter")).click();
        vars.put("win7299", waitForWindow(2000));
        driver.switchTo().window(vars.get("win7299").toString());
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.textToBe(By.xpath("//div[@id=\'bd\']/div/h2"), "Authorize Depositfiles to access your account?"));
        }
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.xpath("(//a[@id=\'google\'])[2]")).click();
        vars.put("win6174", waitForWindow(2000));
        driver.switchTo().window(vars.get("win6174").toString());
        assertThat(driver.getTitle(), is("Вход – Google Аккаунты"));
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.xpath("(//a[@id=\'vkontakte\'])[2]")).click();
        vars.put("win5067", waitForWindow(2000));
        driver.switchTo().window(vars.get("win5067").toString());
        assertEquals(1, driver.findElements(By.xpath("//*[@id=\"oauth_wrap_content\"]/div[1]/a")).size());
        driver.switchTo().window(vars.get("root").toString());
    }
}