// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SwitchLanguageTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void switchLanguage() {
        driver.get("https://dfiles.eu/");
        driver.manage().window().setSize(new Dimension(960, 1053));
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Почему стоит использовать DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[2]")).click();
        driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Why to use DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[3]")).click();
        driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Warum benutzt man DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[4]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("¿Por qué utilizar DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[5]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Por que usar DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[6]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Pourquoi utiliser DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[7]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("DepositFilesを使うの理由は？"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[8]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Waarom gebruikt men DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[9]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Perché usare DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[10]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Varför använder man DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[11]")).click();
        driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("DepositFiles\\\'ı neden kullanıyorsanız?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[12]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Why to use DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[13]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Dlaczego warto skorzystać z DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[14]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Γιατί να χρησιμοποιήσετε την υπηρεσία DepositFiles;"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[15]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Proč používat DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[16]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("為什麼要使用 DepositFiles？"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[17]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("为什么要使用 DepositFiles？"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[18]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("ما هي الفائدة من استخدام DepositFiles؟"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[19]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Hvordan skal man bruke DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a[20]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[3]/div[3]/div/h2")).getText(), is("Для чого використовувати DepositFiles?"));
        driver.findElement(By.xpath("//div[@id=\'foobar\']/div/div/a")).click();
    }
}