// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UploadFileTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void uploadFile() {
        driver.get("https://dfiles.eu/");
        driver.manage().window().setSize(new Dimension(960, 1053));
        driver.findElement(By.cssSelector(".link:nth-child(1) > .sprite")).click();
        driver.findElement(By.name("login")).click();
        driver.findElement(By.name("login")).sendKeys("123");
        driver.findElement(By.cssSelector("#login_frm tr:nth-child(5) > td")).click();
        driver.findElement(By.cssSelector("#login_frm tr:nth-child(3) > td")).click();
        driver.findElement(By.name("login")).click();
        driver.findElement(By.name("login")).sendKeys("gardemarrina");
        driver.findElement(By.cssSelector("#login_frm tr:nth-child(4) > td")).click();
        driver.findElement(By.cssSelector("#login_frm tr:nth-child(5) > td")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("123");
        driver.findElement(By.cssSelector("#login_frm tr:nth-child(4) > td")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("123456");
        driver.findElement(By.cssSelector("#login_frm tr:nth-child(7) > td")).click();
        driver.findElement(By.id("login_btn")).click();
        driver.findElement(By.cssSelector("#uploadifive-file_upload > input:nth-child(2)")).click();
        driver.findElement(By.cssSelector("#uploadifive-file_upload > input:nth-child(2)")).sendKeys("/home/marina/code/FourthYearOfItmo/testing/lab3.side");
        driver.findElement(By.cssSelector(".filename")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".filename"));
            assert(elements.size() > 0);
        }
        assertThat(driver.findElement(By.linkText("OK")).getText(), is("OK"));
        driver.findElement(By.cssSelector(".link:nth-child(2) > strong")).click();
        driver.findElement(By.linkText("Logout")).click();
    }
}