// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ViewTheHelpPageTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        String driverType = System.getenv("DRIVER");
        if(driverType.equals("CHROME")) {
            driver = new ChromeDriver();
        }else if(driverType.equals("FIREFOX")){
            driver = new FirefoxDriver();
        }
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        System.setProperty("webdriver.chrome.driver", "/usr/bin/chromedriver");
        System.setProperty("webdriver.gecko.driver", "/usr/bin/geckodriver");
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void viewTheHelpPage() {
        driver.get("https://dfiles.eu/");
        driver.manage().window().setSize(new Dimension(960, 1053));
        {
            WebElement element = driver.findElement(By.xpath("//a[contains(@class, \'flag_ru\')]"));
            JavascriptExecutor jse = (JavascriptExecutor)driver;
            jse.executeScript("arguments[0].scrollIntoView()", element);
        }
        driver.findElement(By.xpath("//a[contains(@class, \'flag_ru\')]")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[contains(@class, \'active\') and contains(@class, \'flag_ru\')]")));
        }
        driver.findElement(By.xpath("//div[@id=\'main\']/div/ul/li[5]/a")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'main\']/div[4]/div[2]/div/div/div[2]/div"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.xpath("//a[contains(text(),\'Список сайтов-мошенников\')]")).click();
        driver.findElement(By.xpath("//div[@id=\'main\']/div/ul/li[5]/a")).click();
        driver.findElement(By.xpath("//a[contains(text(),\'Пожаловаться\')]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[4]/div/div/ins")).getText(), is("Политика Авторского Права"));
        driver.findElement(By.xpath("//div[@id=\'main\']/div/ul/li[5]/a")).click();
        driver.findElement(By.xpath("//a[contains(text(),\'Ваши отзывы и пожелания\')]")).click();
        js.executeScript("window.scrollTo(0,218)");
        assertThat(driver.findElement(By.xpath("//div[@id=\'main\']/div[4]/div/div/div/ins")).getText(), is("Поддержка"));
        driver.findElement(By.xpath("//div[@id=\'main\']/div/ul/li[5]/a")).click();
    }
}