// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ViewTheHelpPageTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void viewTheHelpPage() {
        driver.get("https://dfiles.eu/");
        driver.manage().window().setSize(new Dimension(960, 1053));
        driver.findElement(By.cssSelector(".help_icon")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".contact_item > .title"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.linkText("Список сайтов-мошенников")).click();
        driver.findElement(By.cssSelector(".help_icon")).click();
        driver.findElement(By.linkText("Пожаловаться")).click();
        assertThat(driver.findElement(By.cssSelector("ins")).getText(), is("Политика Авторского Права"));
        driver.findElement(By.cssSelector(".help_icon")).click();
        driver.findElement(By.linkText("Ваши отзывы и пожелания")).click();
        js.executeScript("window.scrollTo(0,218)");
        assertThat(driver.findElement(By.cssSelector(".title1 > ins")).getText(), is("Поддержка"));
        driver.findElement(By.cssSelector(".help_icon")).click();
    }
}